
version: '2'
services:
    nginx:
        build: ./nginx
        links:
            - repairmytech:repairmytech
        ports:
            - "80:80"
    repairmytech:
        build: .
        container_name: "repairmytech"
        image: debian/latest
        environment:
            - MONGO_URI=mongodb:mongodb:27017/repairmytech
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        # environment:
        #   - MONGO_DATA_DIR=/data/db
        #   - MONGO_LOG_DIR=/dev/null
        # volumes:
        #   - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet